---
title: "BENG183_Project"
author: "Kelsey Dang, Katy Zou, Diego Quintero"
date: "12/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Precision Medicine - Past, Present, & Future

## Table of Contents:
1. Introduction  
2. History of Precision Medicine with focus on Breast Cancer  
3. Genomics in Precision Medicine  
4. Techniques/Methods  
5. Benefits of Precision Medicine  
6. Drawbacks of Precision Medicine  
7. Future Directions  
8. Conclusion  
9. References  
10. Supplementary Material  

## <span style="color:red">1. Introduction</span>

  If every individual on the planet has their own unique genetic makeup, one that distinguishes them from every other person, why are they seen as the same when treating diseases? Each treatment applies differently for each individual, it may or may not be effective, or might not have the same effects on every patient. So how is this problem approached? With Precision Medicine!  
  According to the National Research Council’s Toward Precision Medicine, precision medicine is defined as, “the tailoring of medical treatment to the individual characteristics of each patient”.^1^ Precision Medicine (PM), is being able to improve the treatment for patients, while reducing the need for unnecessary diagnostic testing, therapies, and misdiagnoses. It is a philosophy of medicine that treats patients based on an understanding of their genetics, instead of “assigning” patients to a treatment, a treatment is made catering to the patient.  
  The goal of PM is not only to develop a health care system in which research is carried out in the context of clinical care, but also it is optimizing the treatment and knowledge used to deliver improved patient outcomes.^1^ By incorporating patient data, i.g. DNA, RNA, proteins, metabolism, epigenome, and environmental aspects, Precision Medicine can utilize these essential factors into techniques such as, patient subtyping, biomarker discovery, drug repurposing, and personalized treatment.  
  Today, a large number of precision medicine techniques are implemented to healthcare to help individuals before birth, at birth, and throughout their lifetime. For example, when an expecting mother is about 8 – 12 weeks pregnant, she may have genetic testing to assess any chromosomal abnormalities of the fetus, and the fetus’ entire genome may even be sequenced. At birth, sequencing can be utilized in rapidly diagnosing any factor that may lead to reduced mortality. Throughout an individual’s life, these precision medicine techniques can be used in the diagnosis and treatment of a variety of diseases, especially in accurately diagnosing cancer and applying the correct therapy for chronic diseases.^1^    

## <span style="color:red">2. History of Precision Medicine with focus on Breast Cancer</span>

**insert the history_breastcancer pic**

**1882:** William Halsted performed the first radical mastectomy, a procedure that surgically removes the breast, underlying chest muscle (including pectoralis major and pectoralis minor), and lymph nodes of the axilla.3 This surgery remained the standard breast cancer treatment well into the 20th century.^2^  

**1895:** The first X-ray was taken. Emil Herman Grubbe used X-rays to treat a breast cancer patient.^4^  

**1898:** Marie and Pierre Curie discovered the radioactive elements radium and polonium. Radium was used for radiation therapy on patients but its penetrating abilities were not well understood.^2^   

**1932:** A new, less invasive mastectomy approach was developed.^2^  

**1937:** Radiation therapy is used in conjunction with surgery in order to preserve the breast. The tumor is removed and needles laced with radium are inserted near the breast and lymph nodes.^2^    

**1978:** The anti-estrogen drug tamoxifen is approved by the Food and Drug Administration (FDA) for use in breast cancer treatment. Tamoxifen is part of a new class of drugs called selective estrogen receptor modulators (SERMs) used against cancer. Each cell types’ unique receptor composition allows for selective growth inhibition.5 This is a huge breakthrough in understanding gene and protein interaction pathways.  

**1984:** Researchers discovered the human equivalent gene HER2 in rats. HER2 was aggressive when overexpressed and nonresponsive to treatments, posing a serious dilemma for researchers.^2^    

**1986:** Scientists clone the HER2 gene.  

**1995:** Using cloning technology, scientists can now clone the tumor suppressor genes BRCA1 and BRCA2. Inherited mutations in these two genes predict an increased risk of breast cancer.  

**1996:** The FDA approves anastrozole as an anti-estrogen treatment for breast cancer.  

**1998:** Tamoxifen, another SERM, is found to decrease the risk of developing breast cancer in at-risk men and women by 50%. It is now the most commonly prescribed preventative therapy for “hormone-receptor-positive, early-stage breast cancer after surgery”.6 Trastuzumab, better known as Herceptin, is approved by the FDA. It is used to target patients with HER2 receptor positive breast cancer.^7^    

**April 2003:** Human Genome Project is completed. This allowed the possibility of precision medicine to be widely accepted.  

**2006:** The drug raloxifene was found to reduce breast cancer risk for postmenopausal women who have higher risk.  

**2015:** All of US initiated was founded under the Obama administration in efforts to expand the database for precision medicine focused research.^1^    


## <span style="color:red">Genomics in Precision Medicine</span>

In the first of the charts below, the most widely prescribed breast cancer drugs are listed along with the specific patient type targeted. The second chart lists important biomarkers associated with breast cancer, a description of what the biomarker is, the patient type it affects, and the modern treatment prescribed.  

**Insert "2.1 Popular breast cancer drugs and respective prevision medicine targets"**

**Insert "2.2 Important Biomarkers Identified for Breast Cancer"**

  Genomics is a branch of biology that focuses on understanding genomes and comprises of the central core of precision medicine.^24^ Given the knowledge that every individual’s genetic makeup differs, biomarkers are used in order to identify commonalities between carriers of diseases. In this section, we will focus on genomic biomarkers that identify breast cancer patient types, specifically delving into HER2-positive patients who have an overexpression of the HER2 gene.  
  The discovery of the HER2 gene pathway and its importance in breast cancer growth led to the development of the drug trastuzumab and various other targeted treatments, improving the survival rate of breast cancer patients. The HER2 gene produces proteins that when overexpressed leads to uncontrolled proliferation of epidermal tissue. The two NCI-funded research teams led separately by Dennis Slamon, M.D. and Stuart Aaronson, M.D. were able to discover the “groundbreaking hypothesis that If HER2 could be blocked, the growth of HER2-positive breast cancer might be slowed.”^25^ This was done by showing that high levels of HER2 protein correlate with faster breast cancer growth. A solution they found was to inhibit the actions of the HER2 proteins with special, laboratory produced monoclonal antibodies. So thus, the drug trastuzumab or Herceptin was created.

## <span style="color:red">4. Techniques/Methods</span>

  Precision Medicine can provide a personalized insight into drug treatment and disease diagnosis by using machine learning(ML) and network-based (NB) methods. The issue here, however, is that due to the vast range of biological factors at play in a person’s physiology, it is impossible to create such a diagnosis based solely on just one of these biological markers. The way precision medicine is starting to shift is to using integrative analysis that utilizes two or more of a person’s biological markers simultaneously to create a better prediction.  

Common methods in machine learning fall under three categories:  

**Insert "common methods in machine learning fall under three categories"**

  * <span style="color:red">Supervised:</span> methods are commonly used for classification and regression and require known labels as input with your data. Supervised learning usually involves using a subset of the labeled data as a training set and the remaining of the data as the testing set to determine its accuracy.  
  * <span style="color:red">Unsupervised:</span> methods are commonly used for clustering and dimensionality reduction and take as input a dataset that is unlabeled. For unsupervised learning, hidden patterns can be organized into meaningful subsets.  
  * <span style="color:red">Semisupervised:</span> learning methods takes a mixture of both labeled and unlabeled samples that can be used to explain the structure of the data as well as make new predictions of unlabeled samples.  
  
Example focused on Supervised Learning:  

**Integrating both NB and ML approaches using Proteomics/Interactomics and Transcriptomics and a support vector machine(SVM) to predict Drug response**


## <span style="color:red">5. Benefits of Precision Medicine</span>
## <span style="color:red">6. Drawbacks of Precision Medicine</span>
## <span style="color:red">7. Future Directions</span>
## <span style="color:red">8. Conclusion</span>

Today, the issue that is still presented is finding a way to intertwine PM with other healthcare systems not just within the United States, but also other countries that do not have the adequate knowledge nor treatment for their patients. Ideally with Precision Medicine, it changes the economic agenda and social policies of health not just locally, but globally as well. Despite having a growing number of genomic markers of efficacy and more discoveries of therapeutics for clinical use, there still exists global barriers that prevent precision medicine from making the impact that it has potential for. In order to integrate PM technology into healthcare practice in the future there needs to be changes within the insufficient decision supporting technology and insufficient funding for translational health research.   
Perhaps in the future, economic and social policies will be created to support the progress in precision medicine. This would be essential to the adoption and integration of PM technologies into healthcare not just in the United States, but worldwide. As biomarker discovery accelerates and artificial intelligence-based technologies emerge, and with the help of establishing health care policies that encourage precision medicine, there is potential for the transition from disease treatment, to disease prevention, and all the way to early detection.


## <span style="color:red">9. References</span>
## <span style="color:red">10. Supplementary Material</span>
